services:
  - type: web
    name: luxe-staycations-api
    env: node
    plan: starter
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
    branch: main

databases:
  - name: luxe-redis
    databaseName: luxe_redis
    plan: starter
    ipAllowList: []
