global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'luxe-staycations'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Luxe API metrics
  - job_name: 'luxe-api'
    static_configs:
      - targets: ['luxe-api:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Nginx metrics (if nginx-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s

  # Custom business metrics
  - job_name: 'luxe-business'
    static_configs:
      - targets: ['luxe-api:3001']
    metrics_path: '/api/analytics/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s
    honor_labels: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for common queries
rule_files:
  - "rules/*.yml"
