apiVersion: v1
kind: Namespace
metadata:
  name: luxe-staycations
  labels:
    name: luxe-staycations
    environment: production
    project: luxury-villa-rental
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: luxe-resource-quota
  namespace: luxe-staycations
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: luxe-limit-range
  namespace: luxe-staycations
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    type: Pod
